services:
  typesense:
    image: typesense/typesense:26.0
    restart: on-failure
    ports:
      - "8108:8108"
    volumes:
      - typesense-volume:/data
    command: '--data-dir /data --api-key=xyz --enable-cors'
volumes:
  typesense-volume: